backend/contacts/urls.py
from django.urls import path, include

from . import views

app_name = 'contacts'

urlpatterns = [
    path('api/', include("contacts.api.urls")),
    path('compound-serach/', views.compound_search, name='compound'),
    path('phone-number-search/', views.search_within_contacts_phone_number, name='phone-search'),
    path('import/', views.import_csv, name='import'),
    path('item-detail/<int:pk>/', views.contact_item, name='item-detail'),
    path('list/', views.contacts_list, name='list'),
    path('', views.index, name='index'),
]


# New revised routes
urlpatterns += [
    path('email-search-results-export/', views.export_email_search_results, name='export-selected-emails'),
    path('email-search/', views.search_within_contacts_emails_v2, name='email-search'),
    path('revised/export/', views.export_csv_v2, name='export'),
    path('revised/new-contact/', views.new_contact_v2, name='new'),
    path('revised/delete-contact/<int:pk>/', views.delete_contact_v2, name='delete'),
    path('revised/edit-contact/<int:pk>/', views.contact_edit_v2, name='edit'),
    path('api/', include('contacts.api.urls'))
]

# Django Neapolitan, could act as a backup, maybe
urlpatterns += views.ContactView.get_urls()

backend/home/urls.py
from django.urls import path, include

from . import views

app_name = 'home'

urlpatterns = [
    path('api/', include('home.api.urls')),
    path('', views.IndexPage.as_view(), name='index'),
]

backend/templates/contacts/partials/search/email-search-result.html
<div>
    {% if results %}
        {% for item in results %}
            <p>
                {{ item.email }}
            </p>
        {% empty %}
            <p>
                Nothing found.
            </p>
        {% endfor %}
    {% endif %}
</div>

backend/templates/contacts/partials/search/search-results-container.html
{% load ir_date %}
<div>
    {% if message %}
        {{ message }}
    {% endif %}
    {% if results_count %}
        <h3 class="font-bold text-xl m-4">
          Found {{ results_count }} records.
        </h3>
    {% endif %}
    {% if term %}
        <h3 class="font-bold text-md m-4">
          Searched term: "{{ term }}"
        </h3>
    {% endif %}
    {% if results %}
    <div class="overflow-x-auto">
        <table class="table table-md rounded-box border border-base-content/5 bg-base-200">
          <thead>
            <tr>
                <th></th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Phone Number</th>
                <th>Address</th>
                <th>Created at:</th>
                <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for item in results %}
                <tr>
                    <th>{{ forloop.counter }}</th>
                    <td>{{ item.first_name }}</td>
                    <td>{{ item.last_name }}</td>
                    <td>{{ item.email }}</td>
                    <td>{{ item.phone_number }}</td>
                    <td>{{ item.address }}</td>
                    <td>{{ item.created_at|to_persian }}</td>
                    <td>
                      <button class="btn btn-success btn-outline btn-xs opacity-100 w-14"
                              hx-get="{% url 'contacts:item-detail' pk=item.id %}"
                              hx-trigger="click"
                              hx-target="#data_to_replace"
                              hx-on:success="item_modal.showModal();">
                          View
                      </button>
                    </td>
                    <td>
                      <button class="btn btn-primary btn-outline btn-xs opacity-100 w-14"
                              hx-get="{% url 'contacts:edit' pk=item.id %}"
                              hx-trigger="click"
                              hx-target="#edit_response_holder"
                              hx-on:success="edit_contact_modal_container.showModal();">
                          Edit
                      </button>
                  </td>
                  <td>
                    <button class="btn btn-error btn-outline btn-xs opacity-100 w-14"
                            hx-delete="{% url 'contacts:delete' pk=item.id %}"
                            hx-trigger="click"
                            hx-target="#contacts_container">
                        Delete
                    </button>
                  </td>
                </tr>
            {% endfor %}
          </tbody>
          <tfoot>
          </tfoot>
        </table>
      </div>
    {% endif %}
      <form method="post" action="{% url 'contacts:export-selected-emails' %}">
        {% csrf_token %}
        <input type="text" name="term" value="{{ term }}" hidden>
        <button class="max-w-none btn btn-secondary btn-xs m-5 w-40" type="submit">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m.75 12 3 3m0 0 3-3m-3 3v-6m-1.5-9H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
          </svg>
          Export CSV (filtered)
        </button>
      </form>
</div>