backend/accounts/urls.py
from django.urls import path


from . import views


app_name = 'accounts'
urlpatterns = [
    path('redirect-to-home/', views.redirect_to_home, name='re-home'),
    path('signup/', views.signup_user, name='signup'),
    path('logout/', views.logout_user, name='logout'),
    path('login/', views.login_user, name='login'),
    path('email-login/', views.email_login, name='e-login'),
    path('', views.index, name='index'),
]

backend/home/urls.py
from django.urls import path, include

from . import views

app_name = 'home'

urlpatterns = [
    path('api/', include('home.api.urls')),
    path('', views.IndexPage.as_view(), name='index'),
]

backend/templates/accounts/partials/user-status-partials/logged-in.html
{% load partials %}

{% if user.username and user.email %}
    <div class="flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-12">
            <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
        </svg>
        <div class="ml-2">
            <p class="font-bold">
                Username: {{ user.username }}
            </p>
            <p class="font-bold">
                Email: {{ user.email }}
            </p>
        </div>
    </div>

    <div>
        <button class="btn btn-primary btn-xs m-2 w-20">
            Profile
        </button>
        <button class="btn btn-primary btn-xs m-2 w-20" onclick="logout_modal.showModal()">
            Logout
        </button>
    </div>
    <!-- <button class="btn btn-secondary btn-xs" hx-post="{% url 'accounts:logout' %}" type="button" disabled="disabled">Logout (HTMX)</button> -->
{% endif %}
{% partialdef user-data %}
    {{ user.username }}
    {{ user.email }}
    <button class="btn btn-primary btn-sm" onclick="logout_modal.showModal()">
        Logout
    </button>
    <!-- <button class="btn btn-secondary btn-xs" hx-post="{% url 'accounts:logout' %}" type="button" disabled="disabled">Logout (HTMX)</button> -->
{% endpartialdef user-data %}

backend/templates/accounts/partials/user-status-partials/not-logged-in.html
<div class="m-4">
    <button class="btn btn-primary btn-sm m-4" onclick="signup_modal.showModal()">
        Register
    </button>
    <button class="btn btn-primary btn-sm m-4" onclick="login_modal.showModal()">
        Login
    </button>
    <!-- <a href="{% url 'accounts:e-login' %}">Email Login</a> -->
</div>