backend/contacts/urls.py
from django.urls import path, include

from . import views

app_name = 'contacts'

urlpatterns = [
    path('api/', include("contacts.api.urls")),
    path('compound-serach/', views.compound_search, name='compound'),
    path('phone-number-search/', views.search_within_contacts_phone_number, name='phone-search'),
    path('import/', views.import_csv, name='import'),
    path('item-detail/<int:pk>/', views.contact_item, name='item-detail'),
    path('list/', views.contacts_list, name='list'),
    path('', views.index, name='index'),
]


# New revised routes
urlpatterns += [
    path('email-search-results-export/', views.export_email_search_results, name='export-selected-emails'),
    path('email-search/', views.search_within_contacts_emails_v2, name='email-search'),
    path('revised/export/', views.export_csv_v2, name='export'),
    path('revised/new-contact/', views.new_contact_v2, name='new'),
    path('revised/delete-contact/<int:pk>/', views.delete_contact_v2, name='delete'),
    path('revised/edit-contact/<int:pk>/', views.contact_edit_v2, name='edit'),
    path('api/', include('contacts.api.urls'))
]

# Django Neapolitan, could act as a backup, maybe
urlpatterns += views.ContactView.get_urls()

backend/home/urls.py
from django.urls import path, include

from . import views

app_name = 'home'

urlpatterns = [
    path('api/', include('home.api.urls')),
    path('', views.IndexPage.as_view(), name='index'),
]

backend/templates/contacts/partials/forms/csv-file-import-form.html
{% load widget_tweaks %}
<div>
    {% if form %}
        <h3 class="font-bold text-lg mb-4">Import from CSV file</h3>
        <form 
            class="mb-4 form" 
            hx-encoding="multipart/form-data" 
            hx-post="{% url 'contacts:import' %}"
            hx-target="#import_response_holder"
            hx-swap="innerHTML">
            {% csrf_token %}
            <div class="form-control">
                {{ form.file|add_label_class:"label text-black" }}
                {% render_field form.file class="file-input text-black" type="file" placeholder="file" accept=".csv" %}
            </div>

            <button class="btn btn-primary btn-sm mt-4">
                Confirm
            </button>
        </form>
        <button 
            class="btn btn-error btn-sm mb-4"
            hx-get="{% url 'contacts:list' %}"
            hx-target="#contacts_container"
            hx-on:clean="upload_modal_container.close();console.log('Close.')"
            hx-push-url="true">
                Cancel
        </button>
    {% endif %}
</div>

backend/templates/contacts/partials/forms/item-edit-form.html
{% load widget_tweaks %}
<div id="item_edit_form" class="flex flex-col items-center">
    {% if form %}
        <h3 class="font-bold text-xl mb-4 text-green-600">Edit item</h3>
        <form class="mb-4" id="edit_form">
            {% csrf_token %}
            <p class="mb-4 font-bold">
                Primary Key: {{ item_id }}
            </p>
            <div class="form-control mb-4">
                {{ form.first_name|add_label_class:"label text-black font-bold mb-2" }}
                {% render_field form.first_name class="input" name="first_name" value=form.first_name.value %}
                {% if form.first_name.errors %}
                    <label class="label text-error">
                        {{ form.first_name.errors }}
                    </label>
                {% endif %}
            </div>
            <div class="form-control mb-4">
                {{ form.last_name|add_label_class:"label text-black font-bold mb-2" }}
                {% render_field form.last_name class="input" name="last_name" value=form.last_name.value %}
                {% if form.last_name.errors %}
                    <label class="label text-error">
                        {{ form.last_name.errors }}
                    </label>
                {% endif %}
            </div>
            <div class="form-control mb-4">
                {{ form.email|add_label_class:"label text-black font-bold mb-2" }}
                {% render_field form.email class="input" name="email" value=form.email.value %}
                {% if form.email.errors %}
                    <label class="label text-error">
                        {{ form.email.errors }}
                    </label>
                {% endif %}
            </div>
            <div class="form-control mb-4">
                {{ form.phone_number|add_label_class:"label text-black font-bold mb-2" }}
                {% render_field form.phone_number class="input" name="phone_number" value=form.phone_number.value %}
                {% if form.phone_number.errors %}
                    <label class="label text-error">
                        {{ form.phone_number.errors }}
                    </label>
                {% endif %}
            </div>
            <div class="form-control mb-4">
                {{ form.address|add_label_class:"fieldset-legend font-bold" }}
                {% render_field form.address class="textarea h-24" placeholder="Example: USA, Rhode Island, 52 Spooner St." value=form.address.value %}
                <span class="label text-sm">Optional</span>
                {% if form.address.errors %}
                    <label class="label text-error">
                        {{ form.address.errors }}
                    </label>
                {% endif %}
            </div>
            <button class="btn btn-success btn-xs btn-wide m-4"
                    hx-post="{% url 'contacts:edit' pk=item_id %}"
                    hx-target="#edit_response_holder"
                    hx-on:done="console.log('EDIT OK');">
                Confirm
            </button>
        </form>
        <button 
                class="btn btn-warning btn-xs btn-wide m-4"
                hx-get="{% url 'contacts:list' %}"
                hx-target="#contacts_container"
                hx-on:clean="edit_contact_modal_container.close();"
                hx-push-url="true">
            Cancel
        </button>
    {% else %}
        Form was not aquired.
    {% endif %}
</div>

backend/templates/contacts/partials/forms/new-contact-form.html
{% load widget_tweaks %}
<div id="new_contact_form" class="flex flex-col items-center">
    {% if form %}
    <h3 class="font-bold text-xl mb-4 text-green-600">New Contact Item</h3>
        <div class="flex flex-col items-center">
            <form class="m-2">
                {% csrf_token %}
                <div class="form-control m-4">
                    {{ form.first_name|add_label_class:"label font-bold text-black mb-2" }}
                    {% render_field form.first_name class="input" placeholder="Example: Jake" %}
                    {% if form.first_name.errors %}
                        <label class="label text-error">
                            {{ form.first_name.errors }}
                        </label>
                    {% endif %}
                </div>
                
                <div class="form-control m-4">
                    {{ form.last_name|add_label_class:"label font-bold text-black mb-2" }}
                    {% render_field form.last_name class="input" placeholder="Example: Anderson " %}
                    {% if form.last_name.errors %}
                        <label class="label text-error">
                            {{ form.last_name.errors }}
                        </label>
                    {% endif %}
                </div>
                
                <div class="form-control m-4">
                    {{ form.email|add_label_class:"label font-bold text-black mb-2" }}
                    {% render_field form.email class="input" type="email" placeholder="Example: youremail@provider.com" %}
                    {% if form.email.errors %}
                        <label class="label text-error">
                            {{ form.email.errors }}
                        </label>
                    {% endif %}
                </div>
                
                <div class="form-control m-4">
                    {{ form.phone_number|add_label_class:"label font-bold text-black mb-2" }}
                    {% render_field form.phone_number class="input" type="text" placeholder="Example: 5559992211" %}
                    {% if form.phone_number.errors %}
                        <label class="label text-error">
                            {{ form.phone_number.errors }}
                        </label>
                    {% endif %}
                </div>

                <div class="form-control m-4">
                    {{ form.address|add_label_class:"fieldset-legend font-bold" }}
                    {% render_field form.address class="textarea h-24" placeholder="Example: USA, Rhode Island, 52 Spooner St." %}
                    <span class="label text-sm">Optional</span>
                    {% if form.address.errors %}
                        <label class="label text-error">
                            {{ form.address.errors }}
                        </label>
                    {% endif %}
                </div>

                <button class="btn btn-success btn-xs btn-wide m-4"
                        hx-post="{% url 'contacts:new' %}"
                        hx-target="#response_holder"
                        hx-swap="innerHTML">
                    Submit
                </button>
            </form>
        </div>

        <button class="btn btn-warning btn-xs btn-wide m-4"
                hx-get="{% url 'contacts:list' %}"
                hx-target="#contacts_container"
                hx-on:clean="new_contact_modal_container.close();"
                hx-push-url="true">
            Cancel
        </button>
    {% endif %}
</div>