backend/contacts/api/urls.py
from django.urls import path, include

from . import views
from .routers import router

urlpatterns = [
    path("new/", views.NewContactView.as_view(), name='api_new'),
    path("item/<int:pk>/", views.ContactDetailsView.as_view(), name='api_item'),
    path("list/", views.ContactsListView.as_view(), name='api_list'),
    path('', views.APIIndexView.as_view(), name='api_index')
]


# Routers
urlpatterns += [
    path('set/', include(router.urls))
]

backend/contacts/urls.py
from django.urls import path, include

from . import views

app_name = 'contacts'

urlpatterns = [
    path('api/', include("contacts.api.urls")),
    path('compound-serach/', views.compound_search, name='compound'),
    path('phone-number-search/', views.search_within_contacts_phone_number, name='phone-search'),
    path('import/', views.import_csv, name='import'),
    path('item-detail/<int:pk>/', views.contact_item, name='item-detail'),
    path('list/', views.contacts_list, name='list'),
    path('', views.index, name='index'),
]


# New revised routes
urlpatterns += [
    path('email-search-results-export/', views.export_email_search_results, name='export-selected-emails'),
    path('email-search/', views.search_within_contacts_emails_v2, name='email-search'),
    path('revised/export/', views.export_csv_v2, name='export'),
    path('revised/new-contact/', views.new_contact_v2, name='new'),
    path('revised/delete-contact/<int:pk>/', views.delete_contact_v2, name='delete'),
    path('revised/edit-contact/<int:pk>/', views.contact_edit_v2, name='edit'),
    path('api/', include('contacts.api.urls'))
]

# Django Neapolitan, could act as a backup, maybe
urlpatterns += views.ContactView.get_urls()

backend/home/urls.py
from django.urls import path, include

from . import views

app_name = 'home'

urlpatterns = [
    path('api/', include('home.api.urls')),
    path('', views.IndexPage.as_view(), name='index'),
]

backend/contacts/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Contact


class NewConctactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'email', 'phone_number', 'address')

    # dummy validation
    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if first_name.startswith('x'):
            raise ValidationError('No names start with x!')
        return first_name


class ContactItemEditForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'email', 'phone_number', 'address')

    # dummy validation
    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if first_name.startswith('X'):
            raise ValidationError('No names start with X!')
        return first_name



class CsvFileImportForm(forms.Form):
    file = forms.FileField(label="CSV file:")

backend/contacts/api/views.py
from rest_framework.decorators import api_view
from rest_framework import views
from rest_framework import generics
from rest_framework.response import Response
from rest_framework.request import HttpRequest
from rest_framework import status
from rest_framework import permissions
from rest_framework import viewsets
from rest_framework import status
from django.db.models import QuerySet

from . import serializers
from . import permissions as custom_permissions
from contacts.models import Contact


# listCreateAPIView
# RetrieveUpdateDelete


# test ok
class APIIndexView(views.APIView):
    def get(self, *args, **kwargs) -> Response:
        return Response({'message': "OK"})
    

# test ok
class ContactsListView(generics.ListAPIView):
    permission_classes = ( permissions.IsAuthenticated, )
    serializer_class = serializers.ContactModelSerializer

    def get_queryset(self, *args, **kwargs) -> QuerySet:
        qs: QuerySet = Contact.objects.filter( user = self.request.user )
        return qs
    

# test ok
class ContactDetailsView(generics.RetrieveAPIView):
    serializer_class = serializers.ContactDetailsSerializer
    permission_classes = (
        permissions.IsAuthenticated,
        custom_permissions.IsOwner
    )
    
    def get_queryset(self, *args, **kwargs) -> Contact:
        return Contact.objects.filter( user = self.request.user )
    


class NewContactView(generics.CreateAPIView):
    serializer_class = serializers.CreateNewContactSerializer
    permission_classes = ( permissions.IsAuthenticated, )

    def post(self, request, *args, **kwargs):
        data = {
            'first_name': request.data.get('first_name'),
            'last_name': request.data.get('last_name'),
            'email': request.data.get('email'),
            'phone_number': request.data.get('phone_number'),
            'address': request.data.get('address')
        }

        serializer = serializers.CreateNewContactSerializer(data=data)
        if serializer.is_valid():
            serializer.save(user=request.user)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        


# in actuality, we may only need the following two generic views
class ConactsListCreateView(generics.ListCreateAPIView):
    pass

class ContactsDetailsUpdateDeleteView(generics.RetrieveUpdateDestroyAPIView):
    pass



# test ok
class ContactsViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list` and `retrieve` actions.
    """

    serializer_class = serializers.ContactModelSerializer
    permission_classes = ( permissions.IsAuthenticated, )

    def list(self, request: HttpRequest, *args, **kwargs) -> Response:
        queryset: QuerySet = Contact.objects.filter(user=request.user)
        serializer = serializers.ContactModelSerializer(queryset, many=True)
        return Response(serializer.data)
    
    # this method handles POST, returns 201
    def create(self, request: HttpRequest, *args, **kwargs) -> Response:
        serializer = self.get_serializer(data = request.data)
        serializer.is_valid(raise_exception = True)
        serializer.save(user = request.user)
        return Response(serializer.data, status=status.HTTP_201_CREATED)

    # this may be unnecessary, not sure yet
    def get_queryset(self, *args, **kwargs) -> QuerySet:
        qs: QuerySet = self.request.user.contacts.all()
        return qs

backend/contacts/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http.request import HttpRequest
from django.http.response import HttpResponse, FileResponse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth import mixins
from django.utils.decorators import method_decorator
from django.forms.models import model_to_dict
from django.views.decorators.http import require_http_methods
from django.contrib import messages
from neapolitan.views import CRUDView
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from typing import Any
from http import HTTPStatus
import csv


from config.core.base import PAGE_SIZE
from .models import Contact
from .resources import ContactModelResource
from .filters import ContactFilter
from . import forms
from . import services


# Create your views here.

def index(request: HttpRequest) -> HttpResponse:
    return render(request, "contacts/index.html", status=HTTPStatus.OK)



@login_required
def contacts_list(request: HttpRequest) -> HttpResponse:
    user_contacts_filter = ContactFilter(
        request.GET,
        queryset=request.user.contacts.all()
    )
    paginator = Paginator(user_contacts_filter.qs, per_page=PAGE_SIZE)
    page_number = request.GET.get('page', 1)
    # page_obj = paginator.get_page(page_number)
    page_obj = paginator.page(page_number)
    context = {
        'page_obj': page_obj,
        "filter": user_contacts_filter,
        "new_contact_form": forms.NewConctactForm(),
        "total_contacts": user_contacts_filter.qs.get_total_contacts()
    }
    if request.htmx:
        response = render(request, "contacts/partials/contacts-list-container.html", context)
        response['HX-Trigger'] = "clean"
        return response
    else:
        return render(request, "contacts/contacts-list.html", context)



@login_required
def contact_item(request: HttpRequest, pk: int) -> HttpResponse:
    context = {}
    try:
        contact_item = Contact.objects.get(pk=pk)
        if contact_item.user == request.user:
            context['item'] = contact_item
    except Contact.DoesNotExist as error:
        messages.error(request, "Such contact does not exist, or does not belong to you.")
        return redirect(reverse("contacts:list"))
    except Exception as error:
        messages.error(request, "Sorry, we encountered an unknown problem, please check your input and try again in a while.")
        return redirect(reverse("contacts:list"))
    response = render(request, "contacts/partials/item-data/item.html", context)
    response["HX-Trigger"] = 'success'
    return response



# NOT USED
@login_required
def contact_edit(request: HttpRequest, pk: int) -> HttpResponse:
    context = {}
    try:
        item = Contact.objects.get(pk=pk)
        if item.user != request.user:
            raise Contact.DoesNotExist("Such primary key does not exist, or does not belong to you.")
    except Exception as error:
        print("ERROR -> ", error)
        messages.error(request, "Sorry, such contact does not exist, or does not belong to you.")
        return redirect(reverse("contacts:list"))
    if request.method == "POST":
        form = forms.ContactItemEditForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            context["message"] = "Item edited successfully."
            response = render(request, "contacts/partials/edit-success.html", context)
            response["HX-Trigger"] = "done"
            return response
        else:
            context['form'] = form # will contain errors
            context['item_id'] = item.pk
            response = render(request, "contacts/partials/item-data/item-edit.html", context, status=HTTPStatus.UNPROCESSABLE_ENTITY)
            # if form contains errors, we do not want to replace the current target,
            # we must just replace the modal form itself, with the new form containing errors
            # so we use retarget 
            response['HX-Retarget'] = "#item_data"
            # response['HX-Reswap'] = 'outerHTML' # not necessary in our case
            # response['HX-Trigger-After-Settle'] = "fail" # to keep the modal open - not necessary in our case
            return response
    context['form'] = forms.ContactItemEditForm(initial=model_to_dict(item))
    context['item_id'] = item.pk
    response = render(request, "contacts/partials/item-data/item-edit.html", context)
    response["HX-Trigger"] = 'success'
    return response



@login_required
def contact_edit_v2(request: HttpRequest, pk: int) -> HttpResponse:
    context = {}
    try:
        item = Contact.objects.get(pk=pk)
    except Exception as error:
        messages.error(request, "Sorry, we were unable to aquire this item. It may not exist.")
        return redirect(reverse("contacts:list"))
    if item.user != request.user:
        messages.error(request, "Sorry, such contact does not exist, or does not belong to you.")
        return redirect(reverse("contacts:list"))
    if request.method == "POST":
        form = forms.ContactItemEditForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            context['message'] = "Item edited successfully."
            response = render(request, "contacts/partials/messages/edit-success-message.html", context)
            response["HX-Trigger"] = "done"
            return response
        else:
            context['form'] = form
            context['item_id'] = item.pk
            response = render(request, "contacts/partials/forms/item-edit-form.html", context)
            # response['HX-Retarget'] = "#item_edit_form" # this has no effect
            return response
    context['form'] = forms.ContactItemEditForm(initial=model_to_dict(item))
    context['item_id'] = item.pk
    response = render(request, "contacts/partials/forms/item-edit-form.html", context)
    response['HX-Trigger'] = "success"
    return response



# NOT USED
@login_required
@require_http_methods(["DELETE"])
def delete_contact(request: HttpRequest, pk: int) -> HttpResponse:
    context = {}
    try:
        item_to_delete = Contact.objects.get(pk=pk)
        if item_to_delete.user != request.user:
            raise Contact.DoesNotExist("Such contact does not exist, or does not belong to you.")
    except Exception as error:
        print("ERROR -> ", error)
        messages.error(request, "Sorry, such contact does not exist, or does not belong to you.")
        return redirect(reverse("contacts:list"))
    item_to_delete.delete()
    return redirect(reverse("contacts:list"))



@login_required
@require_http_methods(['DELETE'])
def delete_contact_v2(request: HttpRequest, pk: int):
    item = get_object_or_404(Contact, pk=pk)
    if item.user != request.user:
        raise PermissionDenied("You do not have permission to perform this action.")
    item.delete()
    response = HttpResponse()
    messages.info(request, "Item deleted successfully.")
    response['HX-Redirect'] = reverse("contacts:list")
    return response



# NOT USED
@login_required
def new_contact(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = forms.NewConctactForm(request.POST)
        if form.is_valid():
            new_contact_item = form.save(commit=False)
            new_contact_item.user = request.user
            new_contact_item.save()
            response = render(request, "contacts/partials/new-item-success.html", { 'message': "Item successfully added." })
            response['HX-Trigger'] = "done"
            return response
        else:
            response = render(request, "contacts/partials/item-data/new-item.html", { "form": form }, status=HTTPStatus.UNPROCESSABLE_ENTITY)
            response['HX-Retarget'] = "#new_item_form"
            return response
    context = { 'form': forms.NewConctactForm() }
    response = render(request, "contacts/partials/item-data/new-item.html", context)
    return response



@login_required
def new_contact_v2(request: HttpRequest) -> HttpResponse:
    context = {}
    if request.method == "POST":
        form = forms.NewConctactForm(request.POST)
        if form.is_valid():
            contact: Contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            context['message'] = "New item added successfully."
            response = render(request, "contacts/partials/messages/successful-new-contact-message.html", context, status=HTTPStatus.ACCEPTED)
            response['HX-Target'] = "success"
            return response
        else:
            context['form'] = form
            # if status code is set to unprocessable entitiy (422), form errors feedback will not be displayed
            response = render(request, "contacts/partials/forms/new-contact-form.html", context=context)
            return response
    context['form'] = forms.NewConctactForm()
    return render(request, "contacts/partials/forms/new-contact-form.html", context)



# NOT USED
@login_required
def export_csv(request: HttpRequest) -> FileResponse:
    if request.htmx:
        # if request is done by htmx:
        # this will perform a client side redirect, to this very same url
        # but this time, it won't be htmx request, it will be a regular request
        return HttpResponse( headers={'HX-Redirect': request.get_full_path()} )
    
    # other available formats: json, yaml (requires tablib[yaml])
    response = HttpResponse( services.write_csv(request.user.pk) )
    response['Content-Disposition'] = 'attachment; filename="contacts.csv"'
    return response



@login_required
def export_csv_v2(request: HttpRequest) -> FileResponse:
    if request.htmx:
        return HttpResponse( headers = {'HX-Redirect': request.get_full_path()} )
    
    contacts_filter = ContactFilter(
        request.GET,

backend/templates/contacts/contacts-list.html
{% extends "base.html" %}

{% block content %}
    {% include 'contacts/partials/contact-item-modal.html' %}
    {% include 'contacts/partials/modals/edit-contact-modal-container.html' %}
    {% include 'contacts/partials/modals/import-contacts-modal-container.html' %}
    {% include 'contacts/partials/modals/new-contact-modal-container.html' %}
    {% include 'contacts/partials/modals/search-results-modal-container.html' %}
    <div class="flex flex-col">
        <div class="overflow-x-auto col-span-2" id="contacts_block">
            <h1 class="font-bold text-3xl text-black-500 mb-4 inline-block">
                Contacts
            </h1>
            <div class="mb-4">
                <button 
                    class="btn btn-accent btn-sm m-1" 
                    onclick="new_contact_modal_container.showModal();" 
                    hx-get="{% url 'contacts:new' %}"
                    hx-target="#response_holder">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                        </svg>                                 
                    New
                </button>
                <button
                    class="btn btn-outline btn-secondary btn-sm m-1"
                    hx-get="{% url 'contacts:export' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m.75 12 3 3m0 0 3-3m-3 3v-6m-1.5-9H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
                    </svg>                                                  
                    Export CSV
                </button>
                <button
                    class="btn btn-outline btn-secondary btn-sm m-1"
                    hx-get="{% url 'contacts:import' %}"
                    hx-target="#import_response_holder"
                    onclick="upload_modal_container.showModal();">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m6.75 12-3-3m0 0-3 3m3-3v6m-1.5-15H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
                        </svg>                                
                    Import CSV
                </button>
                <button class="btn btn-primary btn-outline btn-sm m-1"
                        hx-get="{% url 'contacts:list' %}"
                        hx-target="#contacts_container"
                        hx-push-url="true"
                        hx-on:clean="console.log('Refreshing list...')">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0 3.181 3.183a8.25 8.25 0 0 0 13.803-3.7M4.031 9.865a8.25 8.25 0 0 1 13.803-3.7l3.181 3.182m0-4.991v4.99" />
                        </svg>                      
                    Refresh List
                </button>
                <a href="{% url 'contacts:list' %}" class="link ml-4 btn btn-soft btn-info btn-sm">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12c0-1.232-.046-2.453-.138-3.662a4.006 4.006 0 0 0-3.7-3.7 48.678 48.678 0 0 0-7.324 0 4.006 4.006 0 0 0-3.7 3.7c-.017.22-.032.441-.046.662M19.5 12l3-3m-3 3-3-3m-12 3c0 1.232.046 2.453.138 3.662a4.006 4.006 0 0 0 3.7 3.7 48.656 48.656 0 0 0 7.324 0 4.006 4.006 0 0 0 3.7-3.7c.017-.22.032-.441.046-.662M4.5 12l3 3m-3-3-3 3" />
                    </svg>                  
                    Full Refresh
                </a>
            </div>
            <div id="contacts_container">
                {% include 'contacts/partials/contacts-list-container.html' %}
            </div>
        </div>
        <div class="col-span-1">
            <a class="btn btn-primary btn-xs m-2 w-24" href="{% url 'home:index' %}">
                Back to home
            </a>
        </div>
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", (evt) => {
            console.log("Testing custom javascript code in Django + HTMX app");
        });
    </script>
{% endblock content %}

backend/templates/contacts/index.html
{% extends "base.html" %}


{% block content %}
<div id="user-login-status">
    {% include 'accounts/partials/user-status.html' %}
</div>
<div class="m-12">
    <a href="{% url 'contacts:list' %}" class="flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-10 h-10 me-2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M18 18.72a9.094 9.094 0 0 0 3.741-.479 3 3 0 0 0-4.682-2.72m.94 3.198.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0 1 12 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 0 1 6 18.719m12 0a5.971 5.971 0 0 0-.941-3.197m0 0A5.995 5.995 0 0 0 12 12.75a5.995 5.995 0 0 0-5.058 2.772m0 0a3 3 0 0 0-4.681 2.72 8.986 8.986 0 0 0 3.74.477m.94-3.197a5.971 5.971 0 0 0-.94 3.197M15 6.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm6 3a2.25 2.25 0 1 1-4.5 0 2.25 2.25 0 0 1 4.5 0Zm-13.5 0a2.25 2.25 0 1 1-4.5 0 2.25 2.25 0 0 1 4.5 0Z" />
        </svg>
        <span class="text-xl font-bold">View List</span>
    </a>
</div>
{% endblock content %}